language: php

sudo: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - 7.0

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - travis_retry composer selfupdate
  - travis_retry composer --version
  - travis_retry composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

cache:
  directories:
  - vendor
